// <auto-generated />
using System;
using Micro_Gigs;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Micro_Gigs.Migrations
{
    [DbContext(typeof(MicroGigsContext))]
    partial class MicroGigsContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Micro_Gigs.Models.GigApplications", b =>
                {
                    b.Property<int>("ApplicationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ApplicationId"));

                    b.Property<int?>("AdminRating")
                        .HasColumnType("int");

                    b.Property<DateTime>("ApplicationDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("FreelancerId")
                        .HasColumnType("int");

                    b.Property<int>("GigId")
                        .HasColumnType("int");

                    b.Property<string>("InternalNotes")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("ProposalText")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<decimal>("ProposedPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("ApplicationId");

                    b.HasIndex("FreelancerId");

                    b.HasIndex("GigId");

                    b.ToTable("Applications");
                });

            modelBuilder.Entity("Micro_Gigs.Models.GigAssignments", b =>
                {
                    b.Property<int>("AssignmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AssignmentId"));

                    b.Property<decimal>("AgreedPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("AssignedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("CompletionDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("FreelancerId")
                        .HasColumnType("int");

                    b.Property<int>("GigId")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("AssignmentId");

                    b.HasIndex("FreelancerId");

                    b.HasIndex("GigId")
                        .IsUnique();

                    b.ToTable("GIG_ASSIGNMENTS");
                });

            modelBuilder.Entity("Micro_Gigs.Models.GigAttachments", b =>
                {
                    b.Property<int>("AttachmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AttachmentId"));

                    b.Property<string>("FileName")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("FileUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("GigId")
                        .HasColumnType("int");

                    b.Property<DateTime>("UploadedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("UploadedBy")
                        .HasColumnType("int");

                    b.HasKey("AttachmentId");

                    b.HasIndex("GigId");

                    b.HasIndex("UploadedBy");

                    b.ToTable("GIG_ATTACHMENTS");
                });

            modelBuilder.Entity("Micro_Gigs.Models.GigCategories", b =>
                {
                    b.Property<int>("GigCategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("GigCategoryId"));

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("GigCategoryId");

                    b.ToTable("Gig_Categories");
                });

            modelBuilder.Entity("Micro_Gigs.Models.GigReviews", b =>
                {
                    b.Property<int>("ReviewId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ReviewId"));

                    b.Property<int>("AssId")
                        .HasColumnType("int");

                    b.Property<int>("ClientId")
                        .HasColumnType("int");

                    b.Property<string>("Comment")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Rating")
                        .HasColumnType("int");

                    b.Property<DateTime>("ReviewDate")
                        .HasColumnType("datetime2");

                    b.HasKey("ReviewId");

                    b.HasIndex("AssId")
                        .IsUnique();

                    b.HasIndex("ClientId");

                    b.ToTable("GIG_REVIEWS");
                });

            modelBuilder.Entity("Micro_Gigs.Models.Gigs", b =>
                {
                    b.Property<int>("GigId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("GigId"));

                    b.Property<decimal>("Budget")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<int>("ClientId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<DateTime>("DueDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("GigCategoryId")
                        .HasColumnType("int");

                    b.Property<DateTime>("PostedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("GigId");

                    b.HasIndex("ClientId");

                    b.HasIndex("GigCategoryId");

                    b.ToTable("Gigs");
                });

            modelBuilder.Entity("Micro_Gigs.Models.Users", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserId"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("RegistrationDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("UserType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("UserId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Micro_Gigs.Models.GigApplications", b =>
                {
                    b.HasOne("Micro_Gigs.Models.Users", "Freelancer")
                        .WithMany("GigApplications")
                        .HasForeignKey("FreelancerId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Micro_Gigs.Models.Gigs", "Gig")
                        .WithMany("GigApplications")
                        .HasForeignKey("GigId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Freelancer");

                    b.Navigation("Gig");
                });

            modelBuilder.Entity("Micro_Gigs.Models.GigAssignments", b =>
                {
                    b.HasOne("Micro_Gigs.Models.Users", "Freelancer")
                        .WithMany("FreelancerAssignments")
                        .HasForeignKey("FreelancerId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Micro_Gigs.Models.Gigs", "Gig")
                        .WithOne("GigAssignment")
                        .HasForeignKey("Micro_Gigs.Models.GigAssignments", "GigId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Freelancer");

                    b.Navigation("Gig");
                });

            modelBuilder.Entity("Micro_Gigs.Models.GigAttachments", b =>
                {
                    b.HasOne("Micro_Gigs.Models.Gigs", "Gig")
                        .WithMany("GigAttachments")
                        .HasForeignKey("GigId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Micro_Gigs.Models.Users", "UploadedByUser")
                        .WithMany("Uploads")
                        .HasForeignKey("UploadedBy")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Gig");

                    b.Navigation("UploadedByUser");
                });

            modelBuilder.Entity("Micro_Gigs.Models.GigReviews", b =>
                {
                    b.HasOne("Micro_Gigs.Models.GigAssignments", "GigAssignment")
                        .WithOne("Review")
                        .HasForeignKey("Micro_Gigs.Models.GigReviews", "AssId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Micro_Gigs.Models.Users", "Client")
                        .WithMany("ReviewsGiven")
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Client");

                    b.Navigation("GigAssignment");
                });

            modelBuilder.Entity("Micro_Gigs.Models.Gigs", b =>
                {
                    b.HasOne("Micro_Gigs.Models.Users", "Client")
                        .WithMany("PostedGigs")
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Micro_Gigs.Models.GigCategories", "GigCategory")
                        .WithMany("Gigs")
                        .HasForeignKey("GigCategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Client");

                    b.Navigation("GigCategory");
                });

            modelBuilder.Entity("Micro_Gigs.Models.GigAssignments", b =>
                {
                    b.Navigation("Review");
                });

            modelBuilder.Entity("Micro_Gigs.Models.GigCategories", b =>
                {
                    b.Navigation("Gigs");
                });

            modelBuilder.Entity("Micro_Gigs.Models.Gigs", b =>
                {
                    b.Navigation("GigApplications");

                    b.Navigation("GigAssignment")
                        .IsRequired();

                    b.Navigation("GigAttachments");
                });

            modelBuilder.Entity("Micro_Gigs.Models.Users", b =>
                {
                    b.Navigation("FreelancerAssignments");

                    b.Navigation("GigApplications");

                    b.Navigation("PostedGigs");

                    b.Navigation("ReviewsGiven");

                    b.Navigation("Uploads");
                });
#pragma warning restore 612, 618
        }
    }
}
