using System;
using System.ComponentModel.DataAnnotations;
using Microsoft.AspNetCore.Http;

namespace Micro_Gigs.DTOs
{
    // =========================================================
    // GIG ATTACHMENTS INPUT DTO
    // Data transfer object used when uploading a new attachment
    // =========================================================

    public class GigAttachmentsInputDTO
    {
        // =====================================================
        // GIG ID
        // The ID of the associated Gig
        // Must match the primary key type in the Gig model
        // =====================================================

        [Required(ErrorMessage = "Gig ID is required.")]
        [Range(1, int.MaxValue, ErrorMessage = "Gig ID must be a positive integer greater than 0.")]
        public int GigId { get; set; }


        // =====================================================
        // FILE URL
        // Path or URL of the uploaded file
        // =====================================================

        [Required(ErrorMessage = "File URL is required when using JSON upload.")]
        [Url(ErrorMessage = "Invalid URL format. Must start with http or https.")]
        [StringLength(500, ErrorMessage = "File URL cannot exceed 500 characters.")]
        public string? FileUrl { get; set; }
    }


    // =========================================================
    // GIG ATTACHMENTS OUTPUT DTO
    // Data transfer object returned when retrieving attachment details
    // =========================================================

    public class GigAttachmentsOutputDTO
    {
        // =====================================================
        // ATTACHMENT ID
        // Primary key for the attachment
        // Automatically generated by the database
        // =====================================================

        public int AttachmentId { get; set; }


        // =====================================================
        // GIG ID
        // The ID of the associated Gig
        // =====================================================

        public int GigId { get; set; }


        // =====================================================
        // FILE URL
        // Path or URL of the attachment
        // =====================================================

        public string FileUrl { get; set; } = string.Empty;

        // Original file name if available
        public string? FileName { get; set; }


        // =====================================================
        // UPLOADED BY
        // ID of the user who uploaded the file
        // Extracted automatically from the JWT Token
        // =====================================================

        public int UploadedBy { get; set; }
    }

    // =========================================================
    // UPLOAD DTO (multipart/form-data)
    // Used when sending a file via form upload
    // =========================================================
    public class GigAttachmentUploadDTO
    {
        [Required]
        public int GigId { get; set; }

        [Required]
        public IFormFile File { get; set; } = null!;
    }
}